apiVersion: v1
kind: Service
metadata: 
 name: payment
 namespace: roboshop
 labels:
  component: payment
  environment: dev
  tier: backend         
spec:
 selector:
  component: payment
  environment: dev
  tier: backend  
 ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 
