apiVersion: v1 
kind: ConfigMap
metadata: 
  name: mongodb
  namespace: roboshop
  labels:
     project: roboshop
     app: mongodb
     tier: backend  

data:
 MONGO: "true" 
 MONGO_URL: "mongodb://mongodb:27017/catalogue"
