apiVersion: v1 
kind: ConfigMap
metadata:
 name: user
 namespace: roboshop
 labels:
  environment: dev
  component: user
  tier: backend  
data:
  REDIS_URL: 'redis://redis:6379' 
  MONGO_URL: "mongodb://mongodb:27017/users"
  MONGO: "true"