
apiVersion: v1 
kind: Service
metadata:
 name: user
 namespace: roboshop
 labels:
    environment: dev
    component: user
    tier: backend  
spec:
 selector:
    environment: dev
    component: user
    tier: backend
 ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
