
apiVersion: v1 
kind: Service
metadata:
 name: mysql-svc-headless
 namespace: roboshop
 labels:
  component: mysql
  environment: dev
  tier: database

spec:
 clusterIP: None 
 selector:
  component: mysql
  environment: dev
  tier: database
 ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
