apiVersion: v1 
kind: Service
metadata:
 name: mysql
 namespace: roboshop
 labels:
  component: mysql
  environment: dev
  tier: database
spec:
 selector:
  component: mysql
  environment: dev
  tier: database
 ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306