
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mysql
 namespace: roboshop
 labels:
  component: mysql
  environment: dev
  tier: database

spec:
 replicas: 2
 serviceName: "mysql-svc-headless"
 selector:
  matchLabels:
    component: mysql
    environment: dev
    tier: database
 template:
  metadata:
   labels:
     component: mysql
     environment: dev
     tier: database

  spec: 
   containers:
    - name: mysql
      image: {{ .Values.statefulset.imageVersion }}
      envFrom:
       - secretRef:
          name: mysql
      volumeMounts:
       - name: mysql-vol
         mountPath: /var/lib/mysql     

 volumeClaimTemplates:
  metadata:
    name: mysql-vol
  spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "roboshop-ebs-sc"
        resources:
          requests:
            storage: 2Gi   

