apiVersion: v1 
kind: ConfigMap
metadata: 
  name: redis
  namespace: roboshop
  labels:
     project: roboshop
     app: redis
     tier: backend  

data:
 MONGO: "true" 
 MONGO_URL: "mongodb://mongodb:27017/redis"
