
apiVersion: v1
kind: Service
metadata: 
 name: redis
 namespace: roboshop
 labels:
    component: redis
    environment: dev
    tier: database  
spec:
 selector:
  component: redis
  environment: dev
  tier: database
 ports: 
  - protocol: TCP
    port: 6379
    targetPort: 6379
