
apiVersion: v1 
kind: Service
metadata: 
 name: shipping
 namespace: roboshop
 labels: 
  component: shipping
  environment: dev
  tier: backend
spec:
 selector:
  component: shipping
  environment: dev
  tier: backend
 ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
