apiVersion: apps/v1
kind: Deployment
metadata: 
  name: cart
  namespace: roboshop
  labels:
   project: roboshop
   app: cart
   tier: backend
spec:   
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: cart
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        app: cart
        tier: backend
    spec:
      containers:
       - name: cart
         image: harshatejaadduri/cart:v2
         envFrom:
         - configMapRef:
            name: cart
         resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"