apiVersion: apps/v1
kind: Deployment
metadata: 
  name: catalogue
  namespace: roboshop
  labels:
   project: roboshop
   app: catalogue
   tier: backend
spec:   
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: catalogue
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        app: catalogue
        tier: backend
    spec:
      containers:
       - name: catalogue
         image: harshatejaadduri/catalogue:v2
         envFrom:
         - configMapRef:
            name: catalogue
         resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"