apiVersion: v1 
kind: Service
metadata: 
  name: cart
  namespace: roboshop
  labels:
   project: roboshop
   app: cart
   tier: backend
spec:
 selector:
   project: roboshop
   app: cart
   tier: backend
 ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
