apiVersion: v1 
kind: Service
metadata: 
  name: cart
  namespace: roboshop
  labels:
    component: cart
    tier: backend
    environment: dev
spec:
 selector:
    component: cart
    tier: backend
    environment: dev
 ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
