apiVersion: v1
kind: Service
metadata: 
 name: rabbitmq-svc-headless
 namespace: roboshop
 labels: 
    component: rabbitmq
    environment: dev
    tier: database
spec:
 clusterIP: None
 selector:
  component: rabbitmq
  environment: dev
  tier: database
 ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
