
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: rabbitmq
 namespace: roboshop
 labels: 
  component: rabbitmq
  environment: dev
  tier: database
spec:
 replicas: 1
 serviceName: "rabbitmq-svc-headless"
 selector:
  matchLabels:
    component: rabbitmq
    environment: dev
    tier: database
 template: 
  metadata: 
   labels: 
    component: rabbitmq
    environment: dev
    tier: database
  spec:
   containers:
    - name: rabbitmq
      image: rabbitmq:3 
      envFrom:
       - secretRef:
          name: rabbitmq 
      volumeMounts:
       - name: rabbitmq-vol
         mountPath: /var/lib/rabbitmq
 volumeClaimTemplates:
 - metadata:
   name: rabbitmq-vol
   spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "roboshop-ebs-sc"
        resources:
          requests:
            storage: 2Gi  
