
apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontend
 namespace: roboshop
 labels: 
  component: frontend
  environment: dev
  tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend
      environment: dev
      tier: web
  template:
   metadata:
    labels:
        component: frontend
        environment: dev
        tier: web   
   spec:
    containers:
      - name: frontend
        image: {{ .Values.deployment.imageVersion }}
        resources:
         requests:
          cpu: "50m"
          memory: "128Mi"
         limits:
          cpu: "100m"
          memory: "256Mi"
          
        volumeMounts:
          - name: frontend
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
    volumes:
      - name: frontend
        configMap:
          name: frontend
          items:
            - key: nginx.conf
              path: nginx.conf          
