
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    app: catalogue
    tier: backend
spec:
  selector:
    project: roboshop
    app: catalogue
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
